# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
	- checkout

      # Download and cache dependencies
	- restore_cache:
		key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}

	- run: npm install

	- save_cache:
		key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
		paths:
			- "node_modules"

	- run: xvfb-run -a npm run test -- --no-progress --browsers=ChromeNoSandbox --watch=false

	-run: npm run build

	# run tests!
	- run:
		name: Deploy Master to Firebase
		command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN